name: Build and Test

on:
  push:
    branches:
      - main
      - 'feature/**'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

    #   - name: Run Prisma checks
    #     run: yarn prisma validate

      - name: Run Prisma generate
        run: yarn prisma generate

      - name: Run build
        run: yarn build
